### ISSUE TITLE
jni.h: No such file or directory

### ISSUE THREAD

**Issue by harveyc95** [aionnetwork/aion_fastvm#1]
Error from line 5 of `release.h:` 
`cd .. && make jni && cd dist`

![screen shot 2018-02-08 at 3 45 23 pm](https://user-images.githubusercontent.com/6955197/35997684-349d2156-0ce8-11e8-8f4d-5e66293a1d11.png)

Can't find `jni.h`. It was included line 2 of `org_aion_fastvm_FastVM.h`

![screen shot 2018-02-08 at 4 07 31 pm](https://user-images.githubusercontent.com/6955197/35998543-fe4de178-0cea-11e8-910f-fc53953846f1.png)

Can't find `jin.h`

![screen shot 2018-02-08 at 4 14 20 pm](https://user-images.githubusercontent.com/6955197/35998592-23fab478-0ceb-11e8-9aa5-add8a0e6622e.png)

**Comment by yulongnuco** [comment]
Hi @harveyc95, you need to install JDK9 and set the `JAVA_HOME` environment variables.

**Comment by harveyc95** [comment]
@yulongnuco Error was fixed after installing JDK9 and setting `JAVAHOME`. Thanks
