### ISSUE TITLE
About test code in fastVM

### ISSUE THREAD

**Issue by sultana-mnw** [aionnetwork/aion_fastvm#10]
What is the use trivial test code in fastvm and how we can get it ? You people are mention inside the bench mark in FastVM repositories. if i paste the trivial code in the following file Vaion_fastvm/bench/evm/main.cpp then only  i can get the result.

**Comment by yulongaion** [comment]
Most of the Java side unit tests sit in the parent project, https://github.com/aionnetwork/aion. If you need to import the whole aion project before running the tests.

For the C++ side VM tests, please refer to https://github.com/aionnetwork/aion_fastvm/blob/master/tests/main.cpp

For the solidity compiiler test, please refer to https://github.com/aionnetwork/aion_fastvm/blob/master/solidity/tests/main.cpp
